### ISSUE TITLE
[REVIEW] Frontend CI failing since commit e5e29ae — 3 test suites broken

### ISSUE THREAD

**Issue by xarlord** [xarlord/astrology-saas-platform#134]
## Finding
Frontend CI (frontend-test job) has been failing since commit e5e29ae (May 31, 00:07 UTC). 9 consecutive failures on master. The commit that introduced the breakage was: fix: lunar returns React error #31.

## Failing Tests
1. ShareModal.test.tsx:135 - Password input spy called per-character instead of full value. Likely controlled input firing onChange per keystroke.
2. AppLayout.test.tsx:639 - toHaveStyle() mismatch on backgroundColor.
3. AppLayout.mobile.test.tsx:88 - expected 0 to be greater than 0.
4. ChartViewPage.tsx:45 (intermittent) - TypeError: loadChart is not a function in test mock.

## Category
ci

## Severity
high

## Root Cause
Commit e5e29ae modified frontend/src/services/lunarReturn.api.ts but the test failures may be due to test environment issues (JSdom styling, mock ordering) or a dependency change.

## Recommendation
1. Run lint locally to check for ESLint errors
2. Run vitest to reproduce failures
3. Fix ShareModal.test.tsx to use waitFor
4. Fix AppLayout tests for theme-aware assertions
5. Add GitHub Actions ESLint formatter for better CI annotations

**Comment by xarlord** [comment]
✅ Fixed in #153 — updated ChartViewPage test mock (fetchChart→loadChart), chartStore test, and AppLayout store mocks

**Comment by xarlord** [comment]
📊 **Status update**: The `zod` missing dependency (root cause of 3 test suites breaking) has been fixed in PR #162. All 151 test suites now pass locally. The CI should also pass once that PR is merged. If CI passes after merge, this can be closed.

**Comment by xarlord** [comment]
✅ Verified fixed in current master. Frontend tests: 4,447 passed, 0 failed. Backend tests: 1,354 passed, 0 failed. TypeScript: clean on both frontend and backend.
